# File: .github/workflows/workflow.yml

on: [push]

name: AzureCLISample

jobs:
  azure_automation_module_import:
    runs-on: ubuntu-latest 
    steps:
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: New-AzAutomationModule -Name <ModuleName> -ContentLinkUri <ModuleUri> -ResourceGroupName <ResourceGroupName> -AutomationAccountName <AutomationAccountName>

        # Azure CLI version to be used to execute the script. If not provided, latest version is used
        azcliversion: default
